version: '3.8'

services:

  config-server:
    image: ghcr.io/nhnacademy-be12-trillion/config-server:latest
    container_name: config-server
    ports:
      - "10418:10418"
    environment:
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - SERVER_PORT=10418
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIG5AIBAAKCAYEAoZWK9HTy9yrTCR7kUMb3Z4itho/1O20i8djJcFfIKdPZ1G/I\nUtUbtb//y5+cIYP47IOW9uHUmyVg+9+/FgVHYqA53bMMq1vMjeQkUAbKm2SPsOjF\nRJu1s/XpJmFBs5FN24qeIM0KAanNFiiQlAeCJ1TFmVopbOOBwIyGt2nSLD/c1wbG\n1561RXnT5zv5EMST8xJt8II4bQIAsI3NcsJrNJYp7iyQQ58yTemikENj0i46GkOD\ny8eNnbwa39U8TBY8Qp+tgvJt8b4UujMp2l5ZdoeLWNdCnPoeu70Zu8ITnwpvtEUv\n3UZXRf0Frrb38yR3qfyS/RNMXmXIhXQ/zCaz9opRMEcacCCFqXx/0fMdJPCOq4zS\nXejGcMOaShBFt99FZASwIGIISxFZrva0skpZLrD6O3sHeuGNsS03GbtoXL1hmOL9\nLJ8AoEkOJRWBd0qX4D/aqXKiIYcb3beSajSvpNUBfTn2l8zjpfJC/KosLp/c3j5p\n8WQHB7bgOtvAD9GZAgMBAAECggGARjor8/Y2OQWERhUGjzMCiR2GqZK8tzDGPM2H\nM0v7o24/YMyaiKG1kucZIiNDJO/qSsUgYjmhgTKcNaw3rTbrISrZK4lrqrhRraOn\nwp5JBYONzgpE3n48WTQ6OmOPvh8bcx0Kf+ANhs6JY6WKvMOMplJ6NR3SHlC87nZF\nAMc9wNyau1vnJQSF7WW3GuteYxLE6KKsZJj8NChoK1PeJI/qLydKnwkARFuW7fTq\nof+gDVPpDcwlJnabDqCYH4taUwlgQ5lh1Lw25Kwh+lvTVBx66uc/fpwmJwg273Kg\nFktQauWQ58DgbwbYVffQywLE7FmRbeBwiTMBcNvX47X7dpv3fe6c7fEbOcfSHjLv\nz98BKiw0aPOkJyGHwe3AnrhBN0Yb6t5hSgoDK3oq/o8PlF1yf1Z1/oKoONzP2WHM\nGBC16gsO1yJHBrJNPjnc7Qfg9njqIIPyVM+qQBlNnvibdUX0uof/6Uk53z2ffYRt\nRNxmpYPNDeeydlnI7QdJVzXSz3x/AoHBAMlOvHPVpXxxsb8UXtBdwDXD4lMfxFUZ\nuRnL6hWJAkSxsXQEK/lsTBaiAKRSlsh/tCvcHQmpoaoww74TuYGf4twHijMyhXE6\ng2ObdJNzYRet1sJEfZA+Kd3o3XvEMQQFSxoHXdfnrfcBoKmaZJEiW0hyHApZ+m+8\nj5zOW+c1g7evFbDyYxtQioPeowmR51IhU3NAe16hTm07AeqV8GWE0M6Hg1WgVsVf\nX6y2tgIRburp0R69qyvh09FakyfrH1UBKwKBwQDNe/rLza52YG2CkzezUEdKg7EF\nyrhTcLwPmsGIgZCZKoIH4qShdj3QbAo7hu7moSuqJkfyPU+7aH0fgt1nN0L6ZaGu\nKfd2BT8ULB4kdXhouYaJQOEqbASfyHlimosw67so70t1LOQNBRl+EHp3cACNfQKX\nmb1ZiyYZkY5Lsdj0Onen/dkjhFxkfur50jMDWu/LSnl4kuqGGaf5iZt1WRuqbEM3\nLdDfV9XQXdFtI2oSK+6RWVlXQl4BF+ES5L74bksCgcEAl4vvsSBAYavRzPCP5Dr/\nrToXEs7SZeJkh7gMNEQdcgt3dMiDNlVB/rPc2dfW7X+96lrdfV23d8EYSurcd2of\nRddjQeGhtbkAGqd4Hlz41fOnvj4DbOhvakCZJEhxQf6eKC0th5FBVLdj9OpnFR+R\nKrvEwkI0l5OTZc+wPiH6U/i50qjW1URP0rBzeovdYeX2xcfgWEAFI5QNgEV6YWKY\nMzKvO3HmgNWo2AQAhxQKtUxqgsL0rqdmZ6/RIncN8ldbAoHBAIFxDDe+RZyEefe7\nTWdDtuUVuDnxzdOiPJWH40pec/xIbskQ2Kxtk9rrdDazdWMLPDpfCwtp3AQuekOT\naG1QvnyF8SeJgD10aJwIfqRw63ztAfcMS8sxaGhPHUgkGnKizK+orlwN/0rEX56u\nOrdqcq6uhSeCzWjO4x1QN9cvHYAcJKxKmLJq+tjDqrnc1A3VByGEtKhjxCDdoJbt\nPGTb0TW2JVFpJx7KcgJkVzztBjCURCCDrGfvgtAlfr8sIbDVqQKBwAs8bO1VFILU\n20pnoD76fAWdHjNSbBKsJWRX+QdZv2QxDSs4GJ2cu3zZ75cpsVjF1QC6CC7MtW1T\nTiXTvpcD5wgxxP2aAweo9KXPGEhXVvMY045eSSYWH1J8mEGRZ/78RtbOi+fAay8n\n0b8/PzIOUK10bMCODvZULs5yNayGRhq0oQcSt9C4hRaMqm775g7eK47HzBJC7k6a\nUbpA+8CRTsVSITwXXZMWqg3xrr6JTNQKs29xHqcl++nNYPdjUca76Q==\n-----END RSA PRIVATE KEY-----"
    networks:
      - msa-network
  # 첫 번째 유레카 서버 (포트 10419)
  eureka-peer1:
    image: ghcr.io/nhnacademy-be12-trillion/eureka:latest
    container_name: eureka-peer1
    ports:
      - "10419:10419" # 호스트포트:컨테이너포트
    environment:
      - SERVER_PORT=10419
      # 중요: 도커 내부에서는 localhost가 아닌 '서비스 이름(eureka-peer2)'으로 통신해야 합니다.
      - EUREKA_PEER_URL=http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
    networks:
      - msa-network

  # 두 번째 유레카 서버 (포트 10420)
  eureka-peer2:
    image: ghcr.io/nhnacademy-be12-trillion/eureka:latest
    container_name: eureka-peer2
    ports:
      - "10420:10420"
    environment:
      - SERVER_PORT=10420
      # 중요: Peer1을 바라보도록 설정
      - EUREKA_PEER_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/
    networks:
      - msa-network

  gateway-peer1:
    image: ghcr.io/nhnacademy-be12-trillion/gateway:latest
    container_name: gateway-peer1
    ports:
      - "10400:10400"
    environment:
      - SERVER_PORT=10400
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  gateway-peer2:
    image: ghcr.io/nhnacademy-be12-trillion/gateway:latest
    container_name: gateway-peer2
    ports:
      - "10401:10401"
    environment:
      - SERVER_PORT=10401
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  member-peer1:
    image: ghcr.io/nhnacademy-be12-trillion/member-service:latest
    container_name: member-peer1
    ports:
      - "10403:10403"
    environment:
      - SERVER_PORT=10403
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  member-peer2:
    image: ghcr.io/nhnacademy-be12-trillion/member-service:latest
    container_name: member-peer2
    ports:
      - "10404:10404"
    environment:
      - SERVER_PORT=10404
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  book-peer1:
    image: ghcr.io/nhnacademy-be12-trillion/book-service:latest
    container_name: book-peer1
    ports:
      - "10405:10405"
    environment:
      - SERVER_PORT=10405
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  book-peer2:
    image: ghcr.io/nhnacademy-be12-trillion/book-service:latest
    container_name: book-peer2
    ports:
      - "10406:10406"
    environment:
      - SERVER_PORT=10406
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  order-peer1:
    image: ghcr.io/nhnacademy-be12-trillion/order-service:latest
    container_name: order-peer1
    ports:
      - "10407:10407"
    environment:
      - SERVER_PORT=10407
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  order-peer2:
    image: ghcr.io/nhnacademy-be12-trillion/order-service:latest
    container_name: order-peer2
    ports:
      - "10408:10408"
    environment:
      - SERVER_PORT=10408
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  coupon-service:
    image: ghcr.io/nhnacademy-be12-trillion/coupon-service:latest
    container_name: coupon-peer
    ports:
      - "10409:10409"
    environment:
      - SERVER_PORT=10409
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  search-peer1:
    image: ghcr.io/nhnacademy-be12-trillion/coupon-service:latest
    container_name: search-peer1
    ports:
      - "10410:10410"
    environment:
      - SERVER_PORT=10410
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  search-peer2:
    image: ghcr.io/nhnacademy-be12-trillion/coupon-service:latest
    container_name: search-peer2
    ports:
      - "10411:10411"
    environment:
      - SERVER_PORT=10411
      - EUREKA_URL=http://be12-team1:nhnacademy123!@eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@eureka-peer2:10420/eureka/
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
    networks:
      - msa-network

  front-server:
    image: ghcr.io/nhnacademy-be12-trillion/front-server:latest
    container_name: front
    ports:
      - "10402:80"
    networks:
      - msa-network


# 모든 컨테이너가 공유할 네트워크 생성
networks:
  msa-network:
    driver: bridge