version: "3.8"

# 공통 옵션용 anchor 정의
x-common-service: &common-service
  env_file:
    - ./.env # 서비스마다 환경변수 파일 설정
  networks:
    - msa-network # 컨테이너별 네트워크 설정
x-health-default: &health-default
  interval: 10s
  timeout: 3s
  retries: 12

services:
  # ----------------------------------------
  # 핵심 인프라 서비스 (Discovery & Config)
  # ----------------------------------------
  config-server:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/config-server:latest #workflow에서 등록한 이미지 이름과 일치해야함
    container_name: trillion-config-server
    expose:
      - 10418
    environment:    #서버에서 필요한 환경 설정 변수 주입(Eureka Workflow에서 생성한 .env 파일 에서 찾아옴)
      - SERVER_PORT=10418
      - CONFIG_PRIVATE_KEY=${CONFIG_PRIVATE_KEY} #SSH 내부의 keygen 폴더 하위의 github_rsa 공개키, 비밀키 형식을 맞춰서 설정함(config-repo Depoloy키 설정된 상태)
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/ #유레카 서버 주소 입력
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10418/actuator/health" ]  # docker compose ps 로 상태 조회 시 actuator 조회 시도

  # 1. 첫 번째 유레카 서버 (Active Peer)
  eureka-peer1:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/eureka:latest
    container_name: trillion-eureka-peer1
    expose:
      - 10419
    environment:
      - SERVER_PORT=10419
      - EUREKA_PEER_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10419/actuator/health" ]

  # 2. 두 번째 유레카 서버 (Backup Peer)
  eureka-peer2:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/eureka:latest
    container_name: trillion-eureka-peer2
    expose:
      - 10420
    environment:
      - SERVER_PORT=10420
      - EUREKA_PEER_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10420/actuator/health" ]

  # ----------------------------------------
  # API 게이트웨이 서비스 (Load Balancer & Routing)
  # ----------------------------------------
  gateway-peer1:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/gateway:latest
    container_name: trillion-gateway-peer1
    ports:
      - "127.0.0.1:10400:10400"
    environment:
      - SERVER_PORT=10400
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10400/actuator/health" ]

#  gateway-peer2:
#    <<: *common-service
#    image: ghcr.io/nhnacademy-be12-trillion/gateway:latest
#    container_name: trillion-gateway-peer2
#    ports:
#      - "10401:10401"
#    environment:
#      - SERVER_PORT=10401
#      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
#      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
#      - JWT_SECRET=${JWT_SECRET}

  # ----------------------------------------
  # 마이크로서비스 (Member, Book, Order, Coupon, Search)
  # ----------------------------------------
  # 1. 회원 서비스 (Member Service)
  member-peer1:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/member-service:latest
    container_name: trillion-member-peer1
    expose:
      - 10403
    environment:
      - SERVER_PORT=10403
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - PAYCO_CLIENT_ID=${PAYCO_CLIENT_ID}
      - PAYCO_CLIENT_SECRET=${PAYCO_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10403/actuator/health" ]

  member-peer2:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/member-service:latest
    container_name: trillion-member-peer2
    expose:
      - 10404
    environment:
      - SERVER_PORT=10404
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - PAYCO_CLIENT_ID=${PAYCO_CLIENT_ID}
      - PAYCO_CLIENT_SECRET=${PAYCO_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10404/actuator/health" ]

  # 2. 도서 서비스 (Book Service)
  book-peer1:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/book-service:latest
    container_name: trillion-book-peer1
    expose:
      - 10405
    environment:
      - SERVER_PORT=10405
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - ALADIN_TTBKEY=${ALADIN_TTBKEY}
      - GEMINI_KEY=${GEMINI_KEY}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10405/actuator/health" ]

  book-peer2:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/book-service:latest
    container_name: trillion-book-peer2
    expose:
      - 10406
    environment:
      - SERVER_PORT=10406
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - ALADIN_TTBKEY=${ALADIN_TTBKEY}
      - GEMINI_KEY=${GEMINI_KEY}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10406/actuator/health" ]

  # 3. 주문 서비스 (Order Service)
  order-peer1:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/order-service:latest
    container_name: trillion-order-peer1
    expose:
      - 10407
    environment:
      - SERVER_PORT=10407
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - TOSS_KEY=${TOSS_KEY}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10407/actuator/health" ]

  order-peer2:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/order-service:latest
    container_name: trillion-order-peer2
    expose:
      - 10408
    environment:
      - SERVER_PORT=10408
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - TOSS_KEY=${TOSS_KEY}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10408/actuator/health" ]

  # 4. 쿠폰 서비스 (Coupon Service - 단일 인스턴스)
  coupon-service:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/coupon-service:latest
    container_name: trillion-coupon-peer
    expose:
      - 10409
    environment:
      - SERVER_PORT=10409
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10409/actuator/health" ]

  # 5. 검색 서비스 (Search Service)
  search-peer1:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/search-service:latest
    container_name: trillion-search-peer1
    expose:
      - 10410
    environment:
      - SERVER_PORT=10410
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_SEARCH_KEY=${GEMINI_SEARCH_KEY}
      - ES_HOST=${ES_HOST}
      - ES_PASSWORD=${ES_PASSWORD}
      - GEMINI_SEARCH_KEY=${GEMINI_SEARCH_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - RERANKER_BASE_URL=${RERANKER_BASE_URL}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10410/actuator/health" ]

  search-peer2:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/search-service:latest
    container_name: trillion-search-peer2
    expose:
      - 10411
    environment:
      - SERVER_PORT=10411
      - CONFIG_SERVER_URI=http://be12-team1:nhnacademy123!@config-server:10418/
      - EUREKA_URL=http://be12-team1:nhnacademy123!@trillion-eureka-peer1:10419/eureka/,http://be12-team1:nhnacademy123!@trillion-eureka-peer2:10420/eureka/
      - DB_PASSWORD=${DB_PASSWORD}
      - ES_HOST=${ES_HOST}
      - ES_PASSWORD=${ES_PASSWORD}
      - GEMINI_SEARCH_KEY=${GEMINI_SEARCH_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - RERANKER_BASE_URL=${RERANKER_BASE_URL}
    healthcheck:
      <<: *health-default
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:10411/actuator/health" ]

  # ----------------------------------------
  # 프론트엔드 서비스 (Spring Boot / Thymeleaf or Nginx static)
  # ----------------------------------------
  front-server:
    <<: *common-service
    image: ghcr.io/nhnacademy-be12-trillion/front-server:latest
    container_name: trillion-front-peer
    ports:
      - "127.0.0.1:10402:10402"
    environment:
      - SERVER_PORT=10402

  # ----------------------------------------
  # 로그 수집기 Beats
  # ----------------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: trillion-filebeat
    user: root
    networks:
      - msa-network
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: [ "filebeat", "-e", "--strict.perms=false" ]
    restart: unless-stopped



# 모든 컨테이너가 공유할 네트워크 정의
networks:
  msa-network:
    driver: bridge
