spring:
  application:
    name: eureka-server
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: be12-team1
      password: nhnacademy123!

server:
  shutdown: graceful
  # ⚠️ 수정됨: 외부에서 SERVER_PORT를 주입받음 (기본값 8761)
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # ⚠️ 수정됨: 외부에서 상대방 주소(EUREKA_PEER_URL)를 주입받음
      defaultZone: ${EUREKA_PEER_URL}

  instance:
    prefer-ip-address: true
    # 호스트네임은 도커 내부의 호스트네임을 사용
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${server.port}
    registry:
      default-open-for-traffic-count: 0