spring:
  application:
    name: eureka-server
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: be12-team1
      password: nhnacademy123!

server:
  shutdown: graceful
  port: ${SERVER_PORT:10419}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEER_URL}

  instance:
    prefer-ip-address: true
    # 호스트네임은 도커 내부의 호스트네임을 사용
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${server.port}
    registry:
      default-open-for-traffic-count: 0