spring:
  application:
    name: eureka-service
  profiles:
    active: 10420
  security:
    user:
      name: be12-team1
      password: nhnacademy123!

server:
  port: 10420

eureka:
  client:
    register-with-eureka: false # 서버 자체이므로 등록 안 함
    fetch-registry: false # 서버 자체이므로 조회 안 함

    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:10419/eureka/